#!/bin/bash

if [ $# == 0 ]
then
   echo "  usage: $0 komanda"
   echo "example: $0 cat (prikazi sadrzaj svih fajlova u direktoriju)"
   exit 1
else
   CMD=$1
fi
for f in $(ls -r -1 *)
do 
   echo =====; echo $f; echo ======; echo -e
   $CMD $f 
   echo ---------------------------
   echo -e
done
