#!/bin/bash

if [[ ( "$1" == "--help" ) || ( "$1" == "-h" ) ]]
then
   echo "    usage: $0   - zakaci se na builder masinu"
   echo "  example: $0 x - zakaci se na builder masinu sa X protokolom"
   exit 1
else
  if [[ ( "$1" == "x" )  || ( "$1" == "X" ) ]]; then
       PARAMS="-X -C"
       echo "idem sa x .."
   fi
fi

ssh $PARAMS -i ~/.ssh/fljas bringout@192.168.45.114


